name: CI
on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # make sure to update .tool-versions as well!
          hugo-version: "0.147.3"
          extended: true
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Validate data schemas
        run: make validate
      - name: Build
        run: make hugo
